# version: '3.7'

services:
  postgres_account:
    image: postgres:16
    container_name: simbirhealthaccount_postgres
    env_file:
      - ./account/.env
    ports:
      - 5433:5432
    volumes:
      - postgres_account_data:/var/lib/postgresql/data  # Volume for account database

  account_services:
    build:
      context: ./account
    container_name: simbirhealthaccount
    env_file:
      - ./account/.env
    depends_on:
      - postgres_account  
    ports:
      - 8080:8080

  postgres_document:
    image: postgres:16
    container_name: simbirhealthdocument_postgres
    env_file:
      - ./document/.env
    ports:
      - 5434:5432
    volumes:
      - postgres_document_data:/var/lib/postgresql/data  # Volume for document database

  document_services:
    build:
      context: ./document
    container_name: simbirhealthdocument
    env_file:
      - ./document/.env
    depends_on:
      - postgres_document  
    ports:
      - 8083:8083
  
  postgres_hospital:
    image: postgres:16
    container_name: simbirhealthhospital_postgres
    env_file:
      - ./hospital/.env
    ports:
      - 5435:5432
    volumes:
      - postgres_hospital_data:/var/lib/postgresql/data  # Volume for hospital database

  hospital_services:
    build:
      context: ./hospital
    container_name: simbirhealthhospital
    env_file:
      - ./hospital/.env
    depends_on:
      - postgres_hospital 
    ports:
      - 8081:8081
  
  postgres_timetable:
    image: postgres:16
    container_name: simbirhealthtimetable_postgres
    env_file:
      - ./time_table/.env
    ports:
      - 5436:5432
    volumes:
      - postgres_timetable_data:/var/lib/postgresql/data  # Volume for timetable database

  timetable_services:
    build:
      context: ./time_table
    container_name: simbirhealthtimetable
    env_file:
      - ./time_table/.env
    depends_on:
      - postgres_timetable 
    ports:
      - 8082:8082

  # elasticsearch:
  #   image: elasticsearch:8.15.3  # Укажите нужную версию
  #   container_name: elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false  # Отключение безопасности для локальной разработки
  #   ports:
  #     - "9200:9200"  # HTTP порт
  #     - "9300:9300"  # TCP порт (для внутреннего общения между узлами)
  #   volumes:
  #     - elasticsearch-data:/usr/share/elasticsearch/data


volumes:
  postgres_account_data:
  postgres_document_data:
  postgres_hospital_data:
  postgres_timetable_data:
  # elasticsearch-data:
  #   driver: local

