"""add rooms table and delete cascade

Revision ID: b1d23e6972be
Revises: 4864d59fa7f4
Create Date: 2024-10-19 18:02:16.418736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1d23e6972be'
down_revision: Union[str, None] = '4864d59fa7f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rooms_hospital_id_fkey', 'rooms', type_='foreignkey')
    op.create_foreign_key(None, 'rooms', 'hospitals', ['hospital_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.create_foreign_key('rooms_hospital_id_fkey', 'rooms', 'hospitals', ['hospital_id'], ['id'])
    # ### end Alembic commands ###
