from dotenv import load_dotenv
import os

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")
ACCESS_TOKEN_EXPIRE=int(os.getenv("ACCESS_TOKEN_EXPIRE"))
REFRESH_TOKEN_EXPIRE=int(os.getenv("REFRESH_TOKEN_EXPIRE"))
SECRET_KEY=os.getenv("SECRET_KEY")
ALGORITH=os.getenv("ALGORITH")


HOSPITAL_SERVER_URL=os.getenv("HOSPITAL_SERVER_URL")
DOCUMENT_SERVER_URL=os.getenv("DOCUMENT_SERVER_URL")
TIME_TABLE_SERVER_URL=os.getenv("TIME_TABLE_SERVER_URL")

print(f"Database URL: {DATABASE_URL}")

