"""add column gergoerg

Revision ID: 0b5266275d68
Revises: 2de8704325a7
Create Date: 2024-10-16 18:27:54.412456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b5266275d68'
down_revision: Union[str, None] = '2de8704325a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('butcured_time_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_time_table', sa.Integer(), nullable=False),
    sa.Column('from_', sa.DateTime(), nullable=False),
    sa.Column('to', sa.DateTime(), nullable=False),
    sa.Column('enrolled_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_time_table'], ['time_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('time_table', 'enrolled_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_table', sa.Column('enrolled_user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('butcured_time_table')
    # ### end Alembic commands ###
