"""add column gergoergкпуошеппукшщукпщ

Revision ID: e7c39eb35fe9
Revises: 77e787080950
Create Date: 2024-10-16 19:28:25.726125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7c39eb35fe9'
down_revision: Union[str, None] = '77e787080950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('butcured_time_table_id_time_table_fkey', 'butcured_time_table', type_='foreignkey')
    op.create_foreign_key(None, 'butcured_time_table', 'time_table', ['id_time_table'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'butcured_time_table', type_='foreignkey')
    op.create_foreign_key('butcured_time_table_id_time_table_fkey', 'butcured_time_table', 'time_table', ['id_time_table'], ['id'])
    # ### end Alembic commands ###
